name: CMake Build

on: [push]

jobs:
  build-Linux-x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ./build.sh

    - name: Test
      run: |
        ./tests.sh ./build/chameleo

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Linux-x86_64
        path: ./build/chameleo

  build-MacOS-x86_64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ./build.sh

    - name: Test
      run: |
        ./tests.sh ./build/chameleo

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: MacOS-x86_64
        path: ./build/chameleo

  build-MinGW-x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        sudo apt install mingw-w64 libz-mingw-w64-dev

    - name: Build
      run: |
        export CC=/usr/bin/x86_64-w64-mingw32-gcc
        ./build.sh
        mv ./build/chameleo* ./build/chameleo.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: MinGW-x86_64
        path: ./build/chameleo.exe

  test-MinGW-x86_64:
    runs-on: windows-latest
    needs: [build-MinGW-x86_64]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v1
      with:
        name: MinGW-x86_64

    - name: Test
      shell: bash
      run: |
        ./tests.sh ./MinGW-x86_64/chameleo.exe
