name: CMake Build

on: [push]

jobs:
  build-Linux-x86_64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ./build.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Linux-x86_64
        path: ./build/stegano
        
  build-MacOS-x86_64:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ./build.sh
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: MacOS-x86_64
        path: ./build/stegano

  build-MinGW-x86_64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        sudo apt install mingw-w64 libz-mingw-w64-dev
        export CC=/usr/bin/x86_64-w64-mingw32-gcc
      
    - name: Build
      run: |
        ./build.sh
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: MinGW-x86_64
        path: ./build/stegano.exe
